### ISSUE TITLE
Scanning large folder structures with root causes `OutOfMemoryError`

### ISSUE THREAD

**Issue by E0697** [d4rken-org/sdmaid-se#1117]
**Describe the bug**
Since v23, whenever I try to run the AppCleaner scan, it gets to a certain stage and fails.

**To Reproduce**
1. Go to AppCleaner
2. Click on Scan
3. Wait for a while
4. Scan progress is lost

**Expected behavior**
The scan should finish and provide the result

**Smartphone (please complete the following information):**
 - Device: Realme 7 Pro
 - OS: Android 14
 - Root status' Magisk v27
 - SD Maid 2/SE version: v23.2

**Debug log**
[pixeldrain.com](https://pixeldrain.com/u/dH4eiaLK)

**Screenshots/Video**
If applicable, add screenshots or a video if it helps to explain your problem.

**Additional context**
I recall getting a dead object exception some of the times I ran the scan.

**Comment by d4rken** [comment]
Hm

Looks like memory issues:

```
2024-04-04T12:17:42.379Z  D/SDMSE:ShellOps:Service:Host:Root:SharedShell:SR: Acquiring shared resource...
2024-04-04T12:17:42.380Z  D/SDMSE:ShellOps:Service:Host:Root:SharedShell: Initiating connection to host.
2024-04-04T12:17:42.384Z  V/SDMSE:ShellOps:Service:Host:Root:SharedShell:SR: Resource ready: Resource(resource=eu.darken.rxshell.cmd.RxCmdShell$Session@bd42281)
2024-04-04T12:17:42.822Z  V/SDMSE:PkgOps:Service:Host:Root: getInstalledPackagesAsUserStream(131072, 0)...
2024-04-04T12:17:43.407Z  D/SDMSE:PkgOps:Service:Host:Root: getInstalledPackagesAsUser(131072, 0): 736
2024-04-04T12:18:41.576Z  D/SDMSE:Root:Service:Host: checkBase(): Our pkg: android
Shell ids are: [uid=0(root) gid=0(root) groups=0(root) context=u:r:magisk:s0]

2024-04-04T12:20:08.689Z  E/SDMSE:Root:Host#137816380: Uncaught exception within JavaRootHost: java.lang.OutOfMemoryError: Failed to allocate a 8208 byte allocation with 3832 free bytes and 3832B until OOM, target footprint 134217728, growth limit 134217728
	at okio.Segment.<init>(SourceFile:1)
	at okio.SegmentPool.take(Unknown Source:44)
	at okio.Buffer.writableSegment$okio(Unknown Source:43)
	at okio.Buffer.write(Unknown Source:17)
	at okio.Buffer.write(SourceFile:27)
	at rikka.sui.Sui.toRemoteInputStream(Unknown Source:40)
	at eu.darken.sdmse.common.files.local.ipc.FileOpsHost.walkStream(Unknown Source:60)
	at eu.darken.sdmse.common.files.local.ipc.FileOpsConnection$Stub.onTransact(Unknown Source:578)
	at android.os.Binder.execTransactInternal(Binder.java:1358)
	at android.os.Binder.execTransact(Binder.java:1304)
```

SD Maid tries to parcel 736 apps and send them from the root service to SD Maids non root service, this is too large :thinking:

**Comment by d4rken** [comment]
Actually might be the file reading not the apps:

```
2024-04-04T12:21:59.638Z  W/SDMSE:Gateway:Local: walk(path=LocalPath(/data_mirror/data_ce/null/0/com.termux), mode=AUTO) failed:
java.io.IOException: android.os.DeadObjectException
```

I think termux is known for having a lot of small files and substructures, if you exclude it, does it work?

**Comment by E0697** [comment]
You are correct. Termux seems to be the culprit. After the exclusion it works.
It may not be the update to blame. I recently installed a proot filesystem in Termux, which probably contributed to the issue. It just coincided with the update.

**Comment by d4rken** [comment]
I could not reproduce the crash but after setting up termux and installing some packages, it had like 30k+ files and I could see the memory pressure (Pixel 6). A few more packages and it would probably crash too.

For now exclude termux, but I think this is an interesting challenge. I'm looking into streaming the folder data between the processes so it does not have to be loaded into memory all at once.

**Comment by E0697** [comment]
Good to hear that. Hopefully you can work it out. Best of luck!

**Comment by d4rken** [comment]
Did some testing, it required about 400k files on a Nord2 5G to get it to crash due to running out of memory.
The new code managed to read it without crashing:

```
BENCHMARK TOTAL TIME TOOK: 34.861s for 452426 items
```

The AppCleaner takes quite a while to check termux with 450k items here, but it doesn't crash anymore either, though the memory pressure is still high.

For Termux with this many files an exclusion still remains the most efficient solution, but either way cool improvement of SD Maids capabilities :sunglasses:.

**Comment by E0697** [comment]
Great to hear that it works. Thank you!
