### ISSUE TITLE
SD Maid SE crashes

### ISSUE THREAD

**Issue by Ingood5** [d4rken-org/sdmaid-se#116]
Обнаружил ошибку:
1. Открываю SD Maid SE и сворачиваю.
2. Открываю одно или несколько приложений (иногда хватает одного, иногда проблема совсем исчезает).
3. Перехожу в режим смахивания приложений и смахиваю все приложения кроме SD Maid SE
4. Находясь в режиме смахивания жму на SD Maid SE, чтобы открыть его на весь экран.
5. SD Maid SE аварийно завершается (в конце видео он сам закрылся).

[eu.darken.sdmse_logfile_1680857352716.log.zip](https://github.com/d4rken-org/sdmaid-se/files/11177736/eu.darken.sdmse_logfile_1680857352716.log.zip)

**Comment by Ingood5** [comment]
[Screenrecorder-2023-04-07-11-48-04-996.mp4.zip](https://github.com/d4rken-org/sdmaid-se/files/11177756/Screenrecorder-2023-04-07-11-48-04-996.mp4.zip)

**Comment by Ingood5** [comment]
Как на GitHub прикреплять видео, чтобы можно было просматривать прямо в браузере? Забыл😣

**Comment by d4rken** [comment]
No crash visible in the log.

Can you post your install ID? Maybe the automatic reporter caught the crash.

SD Maid > Settings > Support > Install ID

**Comment by Ingood5** [comment]
27b61604-ee64-4968-be16-d54c402fed4c

**Comment by d4rken** [comment]
Thanks, found it. Should be fixed in v0.7.0, can you confirm?

```
eu.darken.sdmse.common.upgrade.core.billing.GplayServiceUnavailableException: Google Play services are unavailable.
        at eu.darken.sdmse.common.upgrade.core.billing.BillingManager$Companion.tryMapUserFriendly$app_gplayBeta(BillingManager.kt:147)
        at eu.darken.sdmse.common.upgrade.core.billing.client.BillingConnection$refreshPurchases$2$iapJob$1.invokeSuspend(BillingConnection.kt:75)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

Caused by: com.android.billingclient.api.BillingResult.getDebugMessage: Service connection is disconnected.
        at eu.darken.sdmse.common.upgrade.core.billing.client.BillingConnection.queryPurchases(BillingConnection.kt:61)
        at eu.darken.sdmse.common.upgrade.core.billing.client.BillingConnection.access$queryPurchases(BillingConnection.kt:22)
        at eu.darken.sdmse.common.upgrade.core.billing.client.BillingConnection$queryPurchases$1.invokeSuspend(Unknown:12)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

**Comment by d4rken** [comment]
Likely #90 or #99

**Comment by Ingood5** [comment]
В 0.7.0 проблема решена 👍
