### ISSUE TITLE
StorageAnalyzer crash

### ISSUE THREAD

**Issue by alabotski** [d4rken-org/sdmaid-se#1173]
**Describe the bug**

**To Reproduce**
1. Go to StorgageAnalyzer
2. Click on 'Scan'

**Expected behavior**

**Smartphone (please complete the following information):**
 - Device: Pixel 7 Pro
 - OS: Android 14
 - Root status rooted
 - SD Maid 2/SE version 0.24.0

**Debug log**
[eu.darken.sdmse_logfile_1716406638227.zip](https://github.com/d4rken-org/sdmaid-se/files/15411852/eu.darken.sdmse_logfile_1716406638227.zip)

**Screenshots/Video**
https://drive.google.com/drive/folders/1FmXMfAH8vaJaAhWLY5WKCjNbupGB3JoJ?usp=drive_link

**Additional context**

**Comment by d4rken** [comment]
Thanks for providing all the details, I love reports like this :heart:.

SD Maid fails to pick the right access method and then gets confused leading to an error :thinking: 

```java
2024-05-22T19:37:25.739Z  V/SDMSE:Analyzer:Storage:Scanner:Extensions: Walking content items for LocalPath(/data/app/~~anSsncUJouWyN8LoGkv5aw==/com.google.android.apps.messaging-G4eAQzmp5O_zUjeQ2BhaEA==)
2024-05-22T19:37:25.739Z  V/SDMSE:Gateway:Local: lookup(AUTO->ROOT): LocalPath(/data/app/~~anSsncUJouWyN8LoGkv5aw==/com.google.android.apps.messaging-G4eAQzmp5O_zUjeQ2BhaEA==)
2024-05-22T19:37:25.739Z  V/SDMSE:Root:Service:Client: runSessionAction(action=interface kotlin.jvm.functions.Function2)
2024-05-22T19:37:25.739Z  V/SDMSE:Root:Service:Client: runModuleAction(moduleClass=class eu.darken.sdmse.common.files.local.ipc.FileOpsClient, action=interface kotlin.jvm.functions.Function2)
2024-05-22T19:37:25.741Z  W/SDMSE:Gateway:Local: lookup(path=LocalPath(/data/app/~~anSsncUJouWyN8LoGkv5aw==/com.google.android.apps.messaging-G4eAQzmp5O_zUjeQ2BhaEA==), mode=AUTO) failed:
eu.darken.sdmse.common.files.ReadException: Can't read from path. <-> /data/app/~~anSsncUJouWyN8LoGkv5aw==/com.google.android.apps.messaging-G4eAQzmp5O_zUjeQ2BhaEA==
	at eu.darken.sdmse.common.files.local.LocalGateway$lookup$3.invokeSuspend(Unknown Source:344)
	at eu.darken.sdmse.common.files.local.LocalGateway$lookup$3.invoke(Unknown Source:12)
	at eu.darken.sdmse.common.files.local.LocalGateway$runIO$2.invokeSuspend(Unknown Source:32)
	at eu.darken.sdmse.common.files.local.LocalGateway$runIO$2.invoke(Unknown Source:12)
	at okio._JvmPlatformKt.startUndispatchedOrReturn(Unknown Source:4)
	at okio.Okio__OkioKt.withContext(Unknown Source:74)
	at eu.darken.sdmse.common.files.local.LocalGateway.runIO(Unknown Source:13)
	at eu.darken.sdmse.common.files.local.LocalGateway.lookup(Unknown Source:10)
	at eu.darken.sdmse.common.files.GatewaySwitch$lookup$3.invokeSuspend(Unknown Source:32)
	at eu.darken.sdmse.common.files.GatewaySwitch$lookup$3.invoke(Unknown Source:12)
	at eu.darken.sdmse.common.files.GatewaySwitch.useGateway(Unknown Source:86)
	at eu.darken.sdmse.common.files.GatewaySwitch.lookup(SourceFile:1)
	at eu.darken.sdmse.analyzer.core.storage.StorageScannerExtensionsKt.walkContentItem(Unknown Source:111)
	at eu.darken.sdmse.analyzer.core.storage.AppStorageScanner.processPkg(Unknown Source:592)
	at eu.darken.sdmse.analyzer.core.storage.StorageScanner.access$scanForApps(Unknown Source:504)
	at eu.darken.sdmse.analyzer.core.storage.StorageScanner$scanForApps$1.invokeSuspend(Unknown Source:12)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.UndispatchedCoroutine.afterResume(Unknown Source:53)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(Unknown Source:22)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:31)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:107)
	at com.google.android.gms.tasks.zzi.run(Unknown Source:34)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Unknown Source:93)
Caused by: java.io.IOException: eu.darken.sdmse.common.files.ReadException: Does not exist or can't be read <-> /data/app/~~anSsncUJouWyN8LoGkv5aw==/com.google.android.apps.messaging-G4eAQzmp5O_zUjeQ2BhaEA==
	at eu.darken.sdmse.common.files.local.ipc.FileOpsClient.toFakeIOException(Unknown Source:71)
	at eu.darken.sdmse.common.files.local.ipc.FileOpsClient.lookUp(Unknown Source:59)
	at eu.darken.sdmse.common.files.local.LocalGateway$lookup$3$3.invokeSuspend(Unknown Source:11)
	at eu.darken.sdmse.common.files.local.LocalGateway$lookup$3$3.invoke(Unknown Source:12)
	at eu.darken.sdmse.common.files.local.LocalGateway$rootOps$2.invokeSuspend(Unknown Source:32)
	at eu.darken.sdmse.common.files.local.LocalGateway$rootOps$2.invoke(Unknown Source:12)
	at eu.darken.sdmse.common.root.service.RootServiceClientExtensionsKt$runModuleAction$2.invokeSuspend(Unknown Source:127)
	at eu.darken.sdmse.common.root.service.RootServiceClientExtensionsKt$runModuleAction$2.invoke(Unknown Source:12)
	at eu.darken.sdmse.common.root.service.RootServiceClient.runSessionAction(Unknown Source:129)
	at eu.darken.sdmse.common.files.local.LocalGateway.access$rootOps(Unknown Source:17)
	at eu.darken.sdmse.common.files.local.LocalGateway$lookup$3.invokeSuspend(Unknown Source:164)
	... 23 more

2024-05-22T19:37:25.742Z  V/SDMSE:SAF:Mapper: Trying to match volume StorageVolumeX(uuid=null, directory=/storage/emulated/0, userlabel=Internal shared storage, volumeX=StorageVolume: Internal shared storage, rootUri=content://com.android.externalstorage.documents/root/primary) against LocalPath(/data/app/~~anSsncUJouWyN8LoGkv5aw==/com.google.android.apps.messaging-G4eAQzmp5O_zUjeQ2BhaEA==)
2024-05-22T19:37:25.743Z  V/SDMSE:CSI:FileForensics:SR: Releasing shared resource...
2024-05-22T19:37:25.743Z  E/SDMSE:TaskManager: execute(): Execution failed (4b4a27cd-4d68-4fbb-af57-80e48917c763): StorageScanTask(target=StorageId(internalId=null, externalId=41217664-9172-527a-b3d5-edabb50a7d69))
java.io.IOException: Can't map LocalPath(/data/app/~~anSsncUJouWyN8LoGkv5aw==/com.google.android.apps.messaging-G4eAQzmp5O_zUjeQ2BhaEA==) to SAF
	at eu.darken.sdmse.common.files.GatewaySwitch.toAlternative(Unknown Source:138)
	at eu.darken.sdmse.common.files.GatewaySwitch.lookup(SourceFile:1)
	at eu.darken.sdmse.analyzer.core.storage.StorageScannerExtensionsKt.walkContentItem(Unknown Source:111)
	at eu.darken.sdmse.analyzer.core.storage.AppStorageScanner.processPkg(Unknown Source:592)
	at eu.darken.sdmse.analyzer.core.storage.StorageScanner.access$scanForApps(Unknown Source:504)
	at eu.darken.sdmse.analyzer.core.storage.StorageScanner$scanForApps$1.invokeSuspend(Unknown Source:12)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.UndispatchedCoroutine.afterResume(Unknown Source:53)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(Unknown Source:22)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:31)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:107)
	at com.google.android.gms.tasks.zzi.run(Unknown Source:34)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Unknown Source:93)
```

**Comment by d4rken** [comment]
That the task aborted could be fixed, the underlying issue is that despite root, this could not be read:

```java
2024-05-22T19:37:25.740Z  V/SDMSE:FileOps:Service:Host:Root: lookUp(LocalPath(/data/app/~~anSsncUJouWyN8LoGkv5aw==/com.google.android.apps.messaging-G4eAQzmp5O_zUjeQ2BhaEA==))...
2024-05-22T19:37:25.740Z  E/SDMSE:FileOps:Service:Host:Root: lookUp(path=LocalPath(/data/app/~~anSsncUJouWyN8LoGkv5aw==/com.google.android.apps.messaging-G4eAQzmp5O_zUjeQ2BhaEA==)) failed
eu.darken.sdmse.common.files.ReadException: Does not exist or can't be read <-> /data/app/~~anSsncUJouWyN8LoGkv5aw==/com.google.android.apps.messaging-G4eAQzmp5O_zUjeQ2BhaEA==
	at com.android.billingclient.api.zzdi.performLookup(Unknown Source:135)
	at eu.darken.sdmse.common.files.local.ipc.FileOpsHost.lookUp(Unknown Source:43)
	at eu.darken.sdmse.common.files.local.ipc.FileOpsConnection$Stub.onTransact(Unknown Source:1175)
	at android.os.Binder.execTransactInternal(Binder.java:1501)
	at android.os.Binder.execTransact(Binder.java:1440)
```

Does it always not work, or does it maybe work on a second try? Was the app being updated at that time?

**Comment by d4rken** [comment]
I'll add a workaround to not abort everything if this happens, but could you manually check out that folder? Do you see any reason why SD Maid wouldn't be able to read it despite having root access?

**Comment by alabotski** [comment]
@d4rken 
Hi

Strange I can't find such folder - /data/app/~~anSsncUJouWyN8LoGkv5aw==

I also record debug info. It still crashes
But without ~~anSsncUJouWyN8LoGkv5aw==

[eu.darken.sdmse_logfile_1716618123221.zip](https://github.com/d4rken-org/sdmaid-se/files/15444707/eu.darken.sdmse_logfile_1716618123221.zip)

**Comment by d4rken** [comment]
This log points into a different direction.

Here the read failed but we see that the reason was that the root service crashes/disconnects:

```java
2024-05-25T06:22:11.101Z  W/SDMSE:Analyzer:Storage:Scanner:Extensions: Failed to walk LocalPath(/data_mirror/data_ce/null/0/com.google.android.apps.diagnosticstool): eu.darken.sdmse.common.files.ReadException: Can't read from path. <-> /data_mirror/data_ce/null/0/com.google.android.apps.diagnosticstool
	at eu.darken.sdmse.common.files.local.LocalGateway$walk$3.invokeSuspend(Unknown Source:600)
(...)
Caused by: java.io.IOException: android.os.DeadObjectException
	at eu.darken.sdmse.common.files.local.ipc.FileOpsClient.toFakeIOException(Unknown Source:71)
	at eu.darken.sdmse.common.files.local.ipc.FileOpsClient.walk(Unknown Source:58)
(...)
```

Service disconnects:

```
2024-05-25T06:22:11.099Z  D/SDMSE:Root:Host:Launcher: onDisconnect(ipc=eu.darken.sdmse.common.root.service.internal.RootConnection$Stub$Proxy@122b79e)
2024-05-25T06:22:11.100Z  D/SDMSE:Root:Host:Launcher: Canceling!
2024-05-25T06:22:11.100Z  D/SDMSE:Root:Host:Launcher: onDisconnect(ipc=eu.darken.sdmse.common.root.service.internal.RootConnection$Stub$Proxy@122b79e)
```

```
2024-05-25T06:22:11.105Z  D/SDMSE:Root:Host:Launcher: Root host launch result was: Cmd.Result(cmd=Cmd(timeout=0, commands=[CLASSPATH=/data/app/~~DF-nfN7Us772zpzBZvAztw==/eu.darken.sdmse-FEJukQb8uwRBJHRlbHIRhw==/base.apk exec /proc/4301/exe -XjdwpProvider:adbconnection -XjdwpOptions:suspend=n,server=y /system/bin --nice-name=eu.darken.sdmse:root:eu.darken.sdmse.common.root.service.RootHost eu.darken.sdmse.common.root.service.RootHost ROOT_HOST_OPTIONS=PQAAAGUAdQAuAGQAYQByAGsAZQBuAC4AcwBkAG0AcwBlAC4AYwBvAG0AbQBvAG4ALgByAG8AbwB0AC4AcwBlAHIAdgBpAGMAZQAuAGkAbgB0AGUAcgBuAGEAbAAuAFIAbwBvAHQASABvAHMAdABJAG4AaQB0AEEAcgBnAHMAAAAPAAAAZQB1AC4AZABhAHIAawBlAG4ALgBzAGQAbQBzAGUAAAAkAAAAZgAyADMAOABjADgAOAA3AC0ANABmADQAMgAtADQAZAA0AGMALQBhAGQAMwA1AC0AMwBlADMANwA1ADQAMwA3ADMANAAzADUAAAAAAAAAAAABAAAAAQAAAAAAAAD/////]), exitcode=-3, output.size()=0, errors.size()=0)
2024-05-25T06:22:11.105Z  E/SDMSE:Root:Service:Client: Failed to establish connection: com.squareup.moshi.JsonEncodingException: Shell died launching the java root host.
	at eu.darken.sdmse.common.root.service.internal.RootHostLauncher$createConnection$1.invokeSuspend(Unknown Source:546)
	at eu.darken.sdmse.common.root.service.internal.RootHostLauncher$createConnection$1.invoke(Unknown Source:12)
	at kotlinx.coroutines.flow.ChannelFlowBuilder.collectTo(Unknown Source:2)
	at kotlinx.coroutines.flow.CallbackFlowBuilder.collectTo(Unknown Source:56)
	at kotlinx.coroutines.flow.internal.ChannelFlow$collectToFun$1.invokeSuspend(Unknown Source:32)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:107)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Unknown Source:93)
```

Is it the latest magisk version? If not could you try updating and rebooting?

**Comment by alabotski** [comment]
@d4rken thanks for your answers 

I use kitsune
[Screenshot_20240528-085248](https://github.com/d4rken-org/sdmaid-se/assets/439337/f2bce028-a28e-4918-978c-591efd56873e)

**Comment by d4rken** [comment]
Does it work if you switch to Magisk? I currently see nothing I could fix on SD Maid's side.
