### ISSUE TITLE
System cleaner not clean properly

### ISSUE THREAD

**Issue by hjymnol** [d4rken-org/sdmaid-se#1199]
**Describe the bug**
System cleaner not working at expected 

**To Reproduce**
1. Using system cleaner
2. Some file still not get delete , delete button still appear

**Expected behavior**
Clean everything

**Smartphone (please complete the following information):**
 - Device: Xiaomi redmi note 12 turbo
 - OS: Android 14
 - Root status : none
 - SD Maid 2 : 0.24.0-beta0

**Debug log**
[eu.darken.sdmse_logfile_1717429027430.log](https://github.com/user-attachments/files/15536445/eu.darken.sdmse_logfile_1717429027430.log)
[eu.darken.sdmse_logfile_1717429027430_shizuku.log](https://github.com/user-attachments/files/15536446/eu.darken.sdmse_logfile_1717429027430_shizuku.log)

**Screenshots/Video**
[Screenshot_2024-06-03-22-23-58-474_eu darken sdmse-edit](https://github.com/d4rken-org/sdmaid-se/assets/23235828/f0250100-4ccf-42e4-8a7b-ce97777df2ed)
[Screenshot_2024-06-03-22-24-09-191_eu darken sdmse](https://github.com/d4rken-org/sdmaid-se/assets/23235828/31d4cddb-1575-4b82-83da-6dfcad85a190)
![Screenshot_2024-06-03-22-26-59-595_eu darken sdmse](https://github.com/d4rken-org/sdmaid-se/assets/23235828/f2eafc53-25e9-4bea-ad0f-d67103fc98ea)

**Additional context**

**Comment by d4rken** [comment]
The files in the screenshot are not deleting?

**Comment by hjymnol** [comment]
Yes, it not deleted and the red delete button still appear

**Comment by hjymnol** [comment]
Fixed with the new 1.0 version

**Comment by hjymnol** [comment]
It seem like scan with shizuku enable not work properly , it can't delete those file

**Comment by d4rken** [comment]
I don't think it's necessarily related but interesting, shizuku log shows this:

```
lookUp(path=LocalPath(/storage/emulated/0/.xlDownload)) failed
eu.darken.sdmse.common.files.ReadException: Does not exist or can't be read <-> /storage/emulated/0/.xlDownload
```

does that file exist? Do you know to which app this file/folder belongs?

**Comment by d4rken** [comment]
The SystemCleaner task fails because this fails:
Don't yet know why though 🤔 

```
2024-06-03T15:37:18.837Z  E/SDMSE:SystemCleaner: Failed to process for eu.darken.sdmse.systemcleaner.core.filter.stock.EmptyDirectoryFilter: eu.darken.sdmse.common.files.WriteException: Can't write to path. <-> /storage/emulated/0/Android/data/com.mojang.minecraftpe/files/games/com.mojang/minecraftpe
	at eu.darken.sdmse.common.files.local.LocalGateway$delete$3.invokeSuspend(Unknown Source:705)
	at eu.darken.sdmse.common.files.local.LocalGateway$delete$3.invoke(Unknown Source:12)
	at eu.darken.sdmse.common.files.local.LocalGateway$runIO$2.invokeSuspend(Unknown Source:32)
	at eu.darken.sdmse.common.files.local.LocalGateway$runIO$2.invoke(Unknown Source:12)
	at okio._JvmPlatformKt.startUndispatchedOrReturn(Unknown Source:4)
	at okio.Okio__OkioKt.withContext(Unknown Source:74)
	at eu.darken.sdmse.common.files.local.LocalGateway.runIO(Unknown Source:13)
	at eu.darken.sdmse.common.files.local.LocalGateway.delete(SourceFile:2)
	at eu.darken.sdmse.common.files.local.LocalGateway.delete(SourceFile:1)
	at eu.darken.sdmse.common.files.GatewaySwitch$delete$2.invokeSuspend(Unknown Source:32)
	at eu.darken.sdmse.common.files.GatewaySwitch$delete$2.invoke(Unknown Source:12)
	at eu.darken.sdmse.common.files.GatewaySwitch.useGateway(Unknown Source:86)
	at eu.darken.sdmse.common.files.GatewaySwitch.delete(Unknown Source:6)
	at eu.darken.sdmse.common.files.APathExtensionsKt.delete(Unknown Source:56)
	at eu.darken.sdmse.common.files.APathExtensionsKt.deleteAll(Unknown Source:282)
	at eu.darken.sdmse.common.files.APathExtensionsKt.deleteAll(Unknown Source:204)
	at eu.darken.sdmse.common.files.APathExtensionsKt$deleteAll$1.invokeSuspend(Unknown Source:10)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.UndispatchedCoroutine.afterResume(Unknown Source:53)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(Unknown Source:22)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:31)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:107)
	at com.google.android.gms.tasks.zzi.run(Unknown Source:34)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Unknown Source:93)
Caused by: java.io.IOException: ADB delete() call returned false
	at eu.darken.sdmse.common.files.local.LocalGateway$delete$3$6.invokeSuspend(Unknown Source:121)
	at eu.darken.sdmse.common.files.local.LocalGateway$delete$3$6.invoke(Unknown Source:12)
	at eu.darken.sdmse.common.files.local.LocalGateway$adbOps$2.invokeSuspend(Unknown Source:32)
	at eu.darken.sdmse.common.files.local.LocalGateway$adbOps$2.invoke(Unknown Source:12)
	at eu.darken.sdmse.common.shizuku.service.ShizukuServiceClientExtensionsKt$runModuleAction$2.invokeSuspend(Unknown Source:127)
	at eu.darken.sdmse.common.shizuku.service.ShizukuServiceClientExtensionsKt$runModuleAction$2.invoke(Unknown Source:12)
	at eu.darken.sdmse.common.shizuku.service.ShizukuServiceClient.runSessionAction(Unknown Source:129)
	at eu.darken.sdmse.common.files.local.LocalGateway.access$adbOps(Unknown Source:17)
	at eu.darken.sdmse.common.files.local.LocalGateway$delete$3.invokeSuspend(Unknown Source:418)
	... 24 more
```

**Comment by hjymnol** [comment]
> I don't think it's necessarily related but interesting, shizuku log shows this:
> 
> ```
> lookUp(path=LocalPath(/storage/emulated/0/.xlDownload)) failed
> eu.darken.sdmse.common.files.ReadException: Does not exist or can't be read <-> /storage/emulated/0/.xlDownload
> ```
> 
> does that file exist? Do you know to which app this file/folder belongs?

Never seen that before but upon search it on Google there is an question about it on xiaomi.eu , I also using xiaomi.eu rom (hyperOs) , I don't know what is that 
https://xiaomi.eu/community/threads/whats-the-xldownload-folder-and-dp_so-log.58584/

**Comment by d4rken** [comment]
> manager

If you look in app control, with system apps showing, can you find a download manager?

**Comment by hjymnol** [comment]
> > Never seen that before but upon search it on Google there is an question about it on xiaomi.eu , I also using xiaomi.eu rom (hyperOs)
> 
> If you look in app control, with system apps showing, can you find a download manager? I'm interested in the package name, then I could add it to cleaning in SD Maid.

Nothing come up , the download manager in my system is just a default download and my aria2

![Screenshot_2024-06-07-23-42-52-929_eu darken sdmse](https://github.com/d4rken-org/sdmaid-se/assets/23235828/3616d81d-aaeb-46a4-ae65-0504b2b0d4df)
![Screenshot_2024-06-07-23-43-49-970_bin mt plus-edit](https://github.com/d4rken-org/sdmaid-se/assets/23235828/264059fd-146d-4a89-9b37-31160da3d041)

**Comment by mcoghlan** [comment]
If it's helpful I'm having trouble running system clean on my Samsung Tab S3.  I get an error "Error - UnsupportedOperationException".  eu.darken.sdmse.common.files.ReadException: Does not exist or can't be read <-> /storage/3362-3663/.android_secure 
I've attached a screen shot and my debug 
[eu.darken.sdmse_logfile_1719334779723.log](https://github.com/user-attachments/files/15976425/eu.darken.sdmse_logfile_1719334779723.log)
![Screenshot_20240625-131008_SD Maid SE](https://github.com/d4rken-org/sdmaid-se/assets/9135967/213d44bd-6a37-49db-8f39-9e2fc4a65d31)
log file

**Comment by mcoghlan** [comment]
The 1.2.0-beta0 corrected this error for me.  Do you want an updated log?

**Comment by d4rken** [comment]
If you can, yes. Would be great to check out for any hidden issues.
