### ISSUE TITLE
App crashes and throws IOException when accessing package list

### ISSUE THREAD

**Issue by dctrbnsttr** [d4rken-org/sdmaid-se#1233]
**Describe the bug**
Since updating to version 1.1.0 beta 0 today, sdmaid-se crashes immediately when starting corpse finder, app cleaner, and app control. This did not occur with prior versions. 

**To Reproduce**
After starting sdmaid-se, if I start any of the above modules individually, the app crashes. 

**Expected behavior**
The modules ought to start up normally. 

**Smartphone (please complete the following information):**
 - Device: Samsung S10 Plus 
 - OS: Android 12
 - Root status Not Rooted, Shizuku on
 - SD Maid 2/SE version 1.1.0 beta 0

**Debug log**
Obtained 

![eu.darken.sdmse_logfile_1718736435651.zip](https://github.com/user-attachments/files/15893284/eu.darken.sdmse_logfile_1718736435651.zip)

**Screenshots/Video**
If applicable, add screenshots or a video if it helps to explain your problem.

**Additional context**

**Comment by unverifiedtx** [comment]
same problem here on my s10+

**Comment by d4rken** [comment]
I think it's an API issue, some calls I changed for support of Android 15 are not available Android 12 (maybe 13 too).

Looking into it. This is the stacktrace:

```java
2024-06-18T19:03:52.961Z  E/SDMSE:PkgOps:Service:Client: getInstalledPackagesAsUserStream(flags=131072, userHandle=UserHandle2(handleId=0)) failed: java.lang.UnsupportedOperationException: java.io.IOException: getInstalledPackagesAsUser(131072,UserHandle2(handleId=0)) failed
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2468)
	at android.os.Parcel.createException(Parcel.java:2440)
	at android.os.Parcel.readException(Parcel.java:2423)
	at android.os.Parcel.readException(Parcel.java:2365)
	at eu.darken.sdmse.common.pkgs.pkgops.ipc.PkgOpsConnection$Stub$Proxy.getInstalledPackagesAsUserStream(Unknown Source:27)
	at eu.darken.sdmse.common.pkgs.pkgops.ipc.PkgOpsClient.getInstalledPackagesAsUserStream(Unknown Source:9)
	at eu.darken.sdmse.common.pkgs.pkgops.PkgOps$queryPkgs$6.invokeSuspend(Unknown Source:13)
	at eu.darken.sdmse.common.pkgs.pkgops.PkgOps$queryPkgs$6.invoke(Unknown Source:12)
	at eu.darken.sdmse.common.pkgs.pkgops.PkgOps$rootOps$2.invokeSuspend(Unknown Source:32)
	at eu.darken.sdmse.common.pkgs.pkgops.PkgOps$rootOps$2.invoke(Unknown Source:12)
	at eu.darken.sdmse.common.root.service.RootServiceClientExtensionsKt$runModuleAction$2.invokeSuspend(Unknown Source:127)
	at eu.darken.sdmse.common.root.service.RootServiceClientExtensionsKt$runModuleAction$2.invoke(Unknown Source:12)
	at eu.darken.sdmse.common.root.service.RootServiceClient.runSessionAction(Unknown Source:129)
	at eu.darken.sdmse.common.pkgs.pkgops.PkgOps.rootOps(Unknown Source:17)
	at eu.darken.sdmse.common.pkgs.pkgops.PkgOps.queryPkgs(SourceFile:1)
	at eu.darken.sdmse.common.pkgs.sources.NormalPkgsSource.access$userSpecific(Unknown Source:180)
	at eu.darken.sdmse.common.pkgs.sources.NormalPkgsSource$userSpecific$1.invokeSuspend(Unknown Source:11)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:107)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Unknown Source:93)

2024-06-18T19:03:52.964Z  E/SDMSE:App: UNCAUGHT EXCEPTION: java.io.IOException: getInstalledPackagesAsUser(131072,UserHandle2(handleId=0)) failed
	at eu.darken.sdmse.common.pkgs.pkgops.ipc.PkgOpsClient.fakeIOException(Unknown Source:62)
	at eu.darken.sdmse.common.pkgs.pkgops.ipc.PkgOpsClient.getInstalledPackagesAsUserStream(Unknown Source:71)
	at eu.darken.sdmse.common.pkgs.pkgops.PkgOps$queryPkgs$6.invokeSuspend(Unknown Source:13)
	at eu.darken.sdmse.common.pkgs.pkgops.PkgOps$queryPkgs$6.invoke(Unknown Source:12)
	at eu.darken.sdmse.common.pkgs.pkgops.PkgOps$rootOps$2.invokeSuspend(Unknown Source:32)
	at eu.darken.sdmse.common.pkgs.pkgops.PkgOps$rootOps$2.invoke(Unknown Source:12)
	at eu.darken.sdmse.common.root.service.RootServiceClientExtensionsKt$runModuleAction$2.invokeSuspend(Unknown Source:127)
	at eu.darken.sdmse.common.root.service.RootServiceClientExtensionsKt$runModuleAction$2.invoke(Unknown Source:12)
	at eu.darken.sdmse.common.root.service.RootServiceClient.runSessionAction(Unknown Source:129)
	at eu.darken.sdmse.common.pkgs.pkgops.PkgOps.rootOps(Unknown Source:17)
	at eu.darken.sdmse.common.pkgs.pkgops.PkgOps.queryPkgs(SourceFile:1)
	at eu.darken.sdmse.common.pkgs.sources.NormalPkgsSource.access$userSpecific(Unknown Source:180)
	at eu.darken.sdmse.common.pkgs.sources.NormalPkgsSource$userSpecific$1.invokeSuspend(Unknown Source:11)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:107)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Unknown Source:93)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@42438bb, Dispatchers.Default]
```

**Comment by d4rken** [comment]
@unverifiedtx Are you also using Shizuku, or Root, or both?

**Comment by unverifiedtx** [comment]
> @unverifiedtx Are you also using Shizuku, or Root, or both?
> 
> Doesn't happen on an Android 8.1 device without Shizuku or Root, seems to be related to accessing packages via Shizuku or Root, i.e. communications across different processes.

I'm also using Shizuku without Root & Android 12 with the Samsung Stock ROM.

[eu.darken.sdmse_logfile_1718795657217.zip](https://github.com/user-attachments/files/15899938/eu.darken.sdmse_logfile_1718795657217.zip)
