### ISSUE TITLE
Error-IOException and crash 

### ISSUE THREAD

**Issue by tommynok** [d4rken-org/sdmaid-se#1234]
**Describe the bug**
Latest version 1.1.0-beta0 FOSS

An Error-IOException occurs when running CorpseАFinder.
Crash (forced stop?) occurs when using AppCleaner

Device information, OS version in logs.
Root Magisk 26.1
[logs-2024-06-18-22-06-32.zip](https://github.com/user-attachments/files/15893178/logs-2024-06-18-22-06-32.zip)
[eu.darken.sdmse_logfile_1718737415416.zip](https://github.com/user-attachments/files/15893179/eu.darken.sdmse_logfile_1718737415416.zip)

**Comment by d4rken** [comment]
Thanks for the log. Let's continue the discussion in #1233 which is the same issue according to the log.

Stacktrace:

```java
2024-06-18T19:03:52.961Z  E/SDMSE:PkgOps:Service:Client: getInstalledPackagesAsUserStream(flags=131072, userHandle=UserHandle2(handleId=0)) failed: java.lang.UnsupportedOperationException: java.io.IOException: getInstalledPackagesAsUser(131072,UserHandle2(handleId=0)) failed
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2468)
	at android.os.Parcel.createException(Parcel.java:2440)
	at android.os.Parcel.readException(Parcel.java:2423)
	at android.os.Parcel.readException(Parcel.java:2365)
	at eu.darken.sdmse.common.pkgs.pkgops.ipc.PkgOpsConnection$Stub$Proxy.getInstalledPackagesAsUserStream(Unknown Source:27)
	at eu.darken.sdmse.common.pkgs.pkgops.ipc.PkgOpsClient.getInstalledPackagesAsUserStream(Unknown Source:9)
	at eu.darken.sdmse.common.pkgs.pkgops.PkgOps$queryPkgs$6.invokeSuspend(Unknown Source:13)
	at eu.darken.sdmse.common.pkgs.pkgops.PkgOps$queryPkgs$6.invoke(Unknown Source:12)
	at eu.darken.sdmse.common.pkgs.pkgops.PkgOps$rootOps$2.invokeSuspend(Unknown Source:32)
	at eu.darken.sdmse.common.pkgs.pkgops.PkgOps$rootOps$2.invoke(Unknown Source:12)
	at eu.darken.sdmse.common.root.service.RootServiceClientExtensionsKt$runModuleAction$2.invokeSuspend(Unknown Source:127)
	at eu.darken.sdmse.common.root.service.RootServiceClientExtensionsKt$runModuleAction$2.invoke(Unknown Source:12)
	at eu.darken.sdmse.common.root.service.RootServiceClient.runSessionAction(Unknown Source:129)
	at eu.darken.sdmse.common.pkgs.pkgops.PkgOps.rootOps(Unknown Source:17)
	at eu.darken.sdmse.common.pkgs.pkgops.PkgOps.queryPkgs(SourceFile:1)
	at eu.darken.sdmse.common.pkgs.sources.NormalPkgsSource.access$userSpecific(Unknown Source:180)
	at eu.darken.sdmse.common.pkgs.sources.NormalPkgsSource$userSpecific$1.invokeSuspend(Unknown Source:11)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:107)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Unknown Source:93)
```
