### ISSUE TITLE
Shizuku and Root service connection fails 

### ISSUE THREAD

**Issue by chaoscalm** [d4rken-org/sdmaid-se#1305]
Tested against latest commit 00e1347fc9fe53fc45fb4b718a5ae2e86eabab93, we get this on granting Magisk permission:

```
FATAL EXCEPTION: javaroot:RootConnectionReceiver#5525ac62-5820-4f49-95ce-4658957f0fe0
Process: eu.darken.sdmse, PID: 9041
kotlin.io.FileSystemException: Failed to get user connection
	at eu.darken.sdmse.common.root.service.internal.RootHostLauncher$createConnection$1$ipcReceiver$1.onConnect(Unknown Source:97)
	at eu.darken.sdmse.common.root.service.internal.RootConnectionReceiver.doOnConnect(Unknown Source:23)
	at eu.darken.sdmse.common.root.service.internal.RootConnectionReceiver.access$doOnConnect(Unknown Source:0)
	at rikka.shizuku.Shizuku$$ExternalSyntheticLambda0.run$eu$darken$sdmse$common$root$service$internal$RootConnectionReceiver$receiver$1$$ExternalSyntheticLambda0(Unknown Source:14)
	at rikka.shizuku.Shizuku$$ExternalSyntheticLambda0.run(Unknown Source:116)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.os.HandlerThread.run(HandlerThread.java:85)

**Comment by chaoscalm** [comment]
Works fine using a debug build, probably it is similar to this bug: https://github.com/d4rken-org/sdmaid-se/issues/689

**Comment by d4rken** [comment]
Inner stacktrace is

```java
getInterfaceFromBinder() failed: java.lang.NoSuchMethodException: eu.darken.sdmse.common.root.service.RootServiceConnection$Stub$Proxy.<init> [interface android.os.IBinder]
                                                     	at java.lang.Class.getConstructor0(Class.java:3395)
                                                     	at java.lang.Class.getDeclaredConstructor(Class.java:3077)
                                                     	at coil.util.-Bitmaps.getInterface(Unknown Source:93)
                                                     	at eu.darken.sdmse.common.root.service.internal.RootHostLauncher$createConnection$1$ipcReceiver$1.onConnect(Unknown Source:50)
                                                     	at eu.darken.sdmse.common.root.service.internal.RootConnectionReceiver.doOnConnect(Unknown Source:23)
                                                     	at eu.darken.sdmse.common.root.service.internal.RootConnectionReceiver.access$doOnConnect(Unknown Source:0)
                                                     	at rikka.shizuku.Shizuku$$ExternalSyntheticLambda0.run$eu$darken$sdmse$common$root$service$internal$RootConnectionReceiver$receiver$1$$ExternalSyntheticLambda0(Unknown Source:14)
                                                     	at rikka.shizuku.Shizuku$$ExternalSyntheticLambda0.run(Unknown Source:116)
                                                     	at android.os.Handler.handleCallback(Handler.java:959)
                                                     	at android.os.Handler.dispatchMessage(Handler.java:100)
                                                     	at android.os.Looper.loopOnce(Looper.java:232)
                                                     	at android.os.Looper.loop(Looper.java:317)
                                                     	at android.os.HandlerThread.run(HandlerThread.java:85)
```

**Comment by d4rken** [comment]
It's an R8 issue, the shrinker is removing the proxy init constructors (or whole class :thinking:)

Currently checking if there is a nicer solution than an R8 rule, this fixes it though:

```
-keepclassmembers class eu.darken.sdmse.common.root.service.RootServiceConnection$Stub$Proxy {
  *;
}
-keepclassmembers class eu.darken.sdmse.common.shizuku.ShizukuServiceConnection$Stub$Proxy {
  *;
}
```

**Comment by d4rken** [comment]
#1305 will fix this, I'm currently thinking about whether we can reasonably catch this and show and error instead of crashing the app. :thinking: 

Maybe even reset the setup state for root/shizuku, so SD Maid does not keep triggering such an issue immediately on every launch.

With this bug you couldn't even open the app any more, though revoking Magisk/Shizuku permission would probably let SD Maid open again :thinking:
