### ISSUE TITLE
IOException error

### ISSUE THREAD

**Issue by catgangdev** [d4rken-org/sdmaid-se#131]
[eu.darken.sdmse_logfile_1681128653706.log.zip](https://github.com/d4rken-org/sdmaid-se/files/11190380/eu.darken.sdmse_logfile_1681128653706.log.zip)

**Describe the bug** 
When press scan on Corpsefinder gives error.

**To Reproduce**
1. Go to Home
2. Click on Scan next to Corpsefinder 
3. See error 

**Expected behavior**
It should scan and show corpse if any

**Smartphone (please complete the following information):**
 - Device: Xiaomi Redmi note 10 pro
 - OS:  Android 13
 - Root status: Rooted - Magisk Delta latest Canary 
 - SD Maid 2/SE version : v0.7.0-rc0

**Screenshots/Video**
Added
![Screenshot_20230410-070200_SD Maid SE](https://user-images.githubusercontent.com/62982051/230808698-1faca82b-e8b7-4458-a214-995924698012.png)

**Comment by d4rken** [comment]
Please provide a debug log of this:
https://github.com/d4rken-org/sdmaid-se/wiki/Bugs#debug-log

**Comment by d4rken** [comment]
Might be fixed by #135, either provide the debug log still, to confirm or wait until the next update.

**Comment by catgangdev** [comment]
> Please provide a debug log of this: https://github.com/d4rken-org/sdmaid-se/wiki/Bugs#debug-log

Log zip added to main post. Check its valid

**Comment by d4rken** [comment]
Great, it's the same issue :). Too much app data for the IPC buffer, which then hits it's limit and the error happens.

```
2023-04-10T12:10:58.554Z  E/SDMSE:Root:Service:PkgOps:Client: getInstalledPackagesAsUser(flags=131072, userHandle=UserHandle2(handleId=0)) failed: android.os.DeadObjectException: Transaction failed on small parcel; remote process probably died, but this could also be caused by running out of binder buffe
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(BinderProxy.java:584)
	at eu.darken.sdmse.common.pkgs.pkgops.root.PkgOpsConnection$Stub$Proxy.getInstalledPackagesAsUser(PkgOpsConnection.java:24)
```
