### ISSUE TITLE
AppCleaner: Shizuku throws error while walking file trees

### ISSUE THREAD

**Issue by dctrbnsttr** [d4rken-org/sdmaid-se#1358]
**Describe the bug**
Sdmaid-se 1.2.2-rc0 crashes when using app cleaner. This did not happen with earlier versions. 

**To Reproduce**
1. Click on app cleaner scan

**Expected behavior**
App cleaner should complete its tasks. 

**Smartphone (please complete the following information):**
 - Device: galaxy s10 plus 
 - OS: Android 12
 - Root status : not rooted. shizuko used
 - SD Maid 2/SE version 1.2.2-rc0 

**Debug log**
If you can reproduce the bug, record the event in [a debug log](https://github.com/d4rken-org/sdmaid-se/wiki/Bugs#debug-log).

**Screenshots/Video**
Screen shot of message after crash included![Screenshot_20240806-184801_SD Maid SE.jpg](https://github.com/user-attachments/assets/f1ddad7a-4570-4ec9-ba21-476095850bd8)

**Additional context**

**Comment by d4rken** [comment]
Does this always happen or only sometimes? Did you try rebooting?

Please provide a debug log of this:
https://github.com/d4rken-org/sdmaid-se/wiki/Bugs#debug-log

This could be an instability with Shizuku where fast file processing causes a crash, or a crash in my code that is excuted within the shizuku service. Can't tell from the error dialog, I'll need a debug look :pray:.

**Comment by dctrbnsttr** [comment]
This happens every time since this most recent update to sd maid se. I have tried clearing cache of the app and rebooting without success. The crash occurs after the search paths are generated, while it is searching. Here is the log file. 

![eu.darken.sdmse_logfile_1723027900883.zip](https://github.com/user-attachments/files/16522361/eu.darken.sdmse_logfile_1723027900883.zip)

**Comment by d4rken** [comment]
Thanks. The error happens when reading a directory (from the Shizuku process) and transferring the found file details back (to SD Maids process).

I can't see a specific cause yet.

* Can you check if this folder contains a lot of files/directories: `/storage/7B41-4618/Android/data/com.crittermap.backcountrynavigator.license` ?
* Did it work with v1.2.1? Maybe this is related to the change in 1aa77126 :thinking: 

```java
java.io.IOException: Remote Exception
	at okio.Buffer$inputStream$1.read(SourceFile:26)
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:291)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:355)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:181)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at java.io.BufferedReader.fill(BufferedReader.java:172)
	at java.io.BufferedReader.readLine(BufferedReader.java:335)
	at java.io.BufferedReader.readLine(BufferedReader.java:400)
	at eu.darken.sdmse.common.files.local.ipc.LocalPathLookupIPCFlowKt$toLocalPathLookupFlow$1.invokeSuspend(Unknown Source:107)
	at eu.darken.sdmse.common.files.local.ipc.LocalPathLookupIPCFlowKt$toLocalPathLookupFlow$1.invoke(Unknown Source:12)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Unknown Source:2)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Unknown Source:68)
	at kotlinx.coroutines.flow.FlowKt.toCollection(Unknown Source:62)
	at kotlinx.coroutines.flow.FlowKt.toList$default(Unknown Source:5)
	at eu.darken.sdmse.appcleaner.core.scanner.AppScanner.readAppDirs(Unknown Source:604)
	at eu.darken.sdmse.appcleaner.core.scanner.AppScanner$readAppDirs$1.invokeSuspend(Unknown Source:12)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.UndispatchedCoroutine.afterResume(Unknown Source:53)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(Unknown Source:22)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:31)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:112)
	at androidx.work.Worker$2.run(Unknown Source:49)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Unknown Source:95)
Caused by: android.os.DeadObjectException
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(BinderProxy.java:635)
	at eu.darken.sdmse.common.ipc.RemoteInputStream$Stub$Proxy.readBuffer(Unknown Source:27)
	at okio.Buffer$inputStream$1.read(SourceFile:24)
	... 23 more
```

**Comment by d4rken** [comment]
Could you repeat the debug log in v1.2.2 but also enable "Trace mode" in the debug settings and force-stop SD Maid beforehand.

I'm wondering whether SD Maid might still be transfering file details from Shizuku's process, and closing the service connection prematurely... :thinking:

**Comment by d4rken** [comment]
If you enable debug mode, there is an extra card at the bottom of the dashboard, but you don't need to do this anymore.

I could reproduce the issue on my test device, it is this problem:

> I'm wondering whether SD Maid might still be transfering file details from Shizuku's process, and closing the service connection prematurely... 🤔

I'm working on a fix, thanks for bringing this to my attention :heart:

**Comment by dctrbnsttr** [comment]
👍
