### ISSUE TITLE
Error: NullPointerExeption

### ISSUE THREAD

**Issue by abyss1247** [d4rken-org/sdmaid-se#18]
![Screenshot_2023-03-25-09-40-50-45_a65106d178f5bee05a749e7f17331c4b](https://user-images.githubusercontent.com/116548657/227679086-10c53498-3e21-4c2c-a4f0-7985c9bba9d4.jpg)

**Comment by d4rken** [comment]
When does this happen?

Can you reproduce and record it in a debug log (Settings>Support>Debug log)?

**Comment by abyss1247** [comment]
[eu.darken.sdmse_logfile_1679757431583.log](https://github.com/d4rken-org/sdmaid-se/files/11069234/eu.darken.sdmse_logfile_1679757431583.log)

**Comment by d4rken** [comment]
Thanks! Stacktrace:

```
2023-03-25T15:17:16.567Z  D/SDMSE:Dashboard:Fragment:VM: false | null | null
2023-03-25T15:17:16.567Z  E/SDMSE:TaskManager: execute(): Execution failed (e012a046-bbd6-4058-8449-0b3d49eead18): AppCleanerScanTask(pkgIdFilter=[])
java.lang.NullPointerException: it must not be null
	at eu.darken.sdmse.appcleaner.core.forensics.filter.DefaultCachesPublicFilter.<init>(DefaultCachesPublicFilter.kt:34)
	at eu.darken.sdmse.DaggerApp_HiltComponents_SingletonC$SingletonCImpl$SwitchingProvider.get1(DaggerApp_HiltComponents_SingletonC.java:2348)
	at eu.darken.sdmse.DaggerApp_HiltComponents_SingletonC$SingletonCImpl$SwitchingProvider.get(DaggerApp_HiltComponents_SingletonC.java:28)
	at dagger.internal.SingleCheck.get(SingleCheck.java:14)
	at eu.darken.sdmse.appcleaner.core.forensics.filter.DefaultCachesPublicFilter$Factory.create(DefaultCachesPublicFilter.kt:3)
	at eu.darken.sdmse.appcleaner.core.scanner.AppScanner.initialize(AppScanner.kt:241)
	at eu.darken.sdmse.appcleaner.core.AppCleaner.access$performScan(AppCleaner.kt:111)
	at eu.darken.sdmse.appcleaner.core.AppCleaner$submit$2$result$1.invokeSuspend(AppCleaner.kt:62)
	at eu.darken.sdmse.appcleaner.core.AppCleaner$submit$2$result$1.invoke(AppCleaner.kt:14)
	at eu.darken.sdmse.common.sharedresource.SharedResourceExtensionsKt.keepResourcesAlive(SharedResourceExtensions.kt:214)
	at eu.darken.sdmse.common.sharedresource.SharedResourceExtensionsKt$keepResourcesAlive$1.invokeSuspend(Unknown Source:10)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:107)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:12)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:3)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:82)
```
