### ISSUE TITLE
Integration with Shizuku Doesn't Work Properly

### ISSUE THREAD

**Issue by E0697** [d4rken-org/sdmaid-se#433]
**Describe the bug**
When trying to enable Shizuku support, the app requests access but doesn't recognize it properly when granted.
The app also stops working when access  is enabled (see attached video).

**To Reproduce**
1. Go to Setup
2. Click on Use Shizuku
3. Grant access
4. Access isn't recognized properly (options are greyed out but still says waiting for link)

**Expected behavior**
The granted access should be recognized properly.

**Smartphone (please complete the following information):**
 - Device: Realme 7 Pro
 - OS: Android 12
 - Root status: None
 - SD Maid 2/SE version: v0.10.0-beta

**Debug log**
[eu.darken.sdmse_logfile_1687942571917.log.zip (pixeldrain.com)](https://pixeldrain.com/u/bPFGM5oK)

**Screenshots/Video**
https://github.com/d4rken-org/sdmaid-se/assets/66939100/b4dec48d-69be-4a2c-a660-2d611b56ab8c

**Additional context**
When granting access from Shizuku before launching SD Maid, it doesn't load properly anymore.
When requesting access from SD Maid, it continues to work but with brolen integration until the next launch.

**Comment by d4rken** [comment]
Thanks for the bug report :heart:.
Trying to reproduce atm. This looks interesting:

```java
11:25:58.621 audit                                E  type=1327 audit(1687944358.619:3868): proctitle="eu.darken.sdmse:SDMSE:Shizuku"
11:25:58.648 ShizukuServiceStarter                W  unable to start service eu.darken.sdmse/eu.darken.sdmse.common.shizuku.service.ShizukuHost...
                                                     java.lang.InstantiationException: java.lang.Class<eu.darken.sdmse.common.shizuku.service.ShizukuHost> cannot be instantiated
                                                     	at java.lang.Class.newInstance(Native Method)
                                                     	at rikka.shizuku.fh0.a(SourceFile:25)
                                                     	at moe.shizuku.starter.ServiceStarter.main(SourceFile:4)
                                                     	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
                                                     	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:378)
11:25:58.648 eu.darken.sdmse:SDMSE:Shizuku        I  System.exit called, status: 1
```

**Comment by E0697** [comment]
Happy to help. Thank you for taking the time!

Could be, I'm ready to test it.

**Comment by E0697** [comment]
Thank you for the quick fix!

**Comment by E0697** [comment]
I'm getting this error in the log file when deleting caches via Shizuku. It reverts back to accessibility service:
`2023-06-28T12:19:20.744Z  W/SDMSE:PkgOps: trimCaches(9223372036854775807, null,AUTO) failed: java.io.IOException: android.os.DeadObjectException
	at eu.darken.sdmse.common.pkgs.pkgops.ipc.PkgOpsClient.fakeIOException(Unknown Source:62)
	at eu.darken.sdmse.common.pkgs.pkgops.ipc.PkgOpsClient.trimCaches(Unknown Source:185)
	at eu.darken.sdmse.common.pkgs.pkgops.PkgOps$trimCaches$4.invokeSuspend(Unknown Source:34)
	at eu.darken.sdmse.common.pkgs.pkgops.PkgOps$trimCaches$4.invoke(Unknown Source:12)
	at eu.darken.sdmse.common.pkgs.pkgops.PkgOps$adbOps$2.invokeSuspend(Unknown Source:32)
	at eu.darken.sdmse.common.pkgs.pkgops.PkgOps$adbOps$2.invoke(Unknown Source:12)
	at eu.darken.sdmse.common.shizuku.service.ShizukuServiceClientExtensionsKt$runModuleAction$2.invokeSuspend(Unknown Source:123)
	at eu.darken.sdmse.common.shizuku.service.ShizukuServiceClientExtensionsKt$runModuleAction$2.invoke(Unknown Source:12)
	at eu.darken.sdmse.common.shizuku.service.ShizukuServiceClient.runSessionAction(Unknown Source:129)
	at eu.darken.sdmse.common.pkgs.pkgops.PkgOps.adbOps(Unknown Source:17)
	at eu.darken.sdmse.common.pkgs.pkgops.PkgOps.trimCaches(Unknown Source:301)
	at eu.darken.sdmse.appcleaner.core.deleter.AppJunkDeleter.deleteInaccessible(Unknown Source:489)
	at eu.darken.sdmse.appcleaner.core.AppCleaner$performDelete$inaccessibleSuccesses$1.invokeSuspend(Unknown Source:216)
	at eu.darken.sdmse.appcleaner.core.AppCleaner$performDelete$inaccessibleSuccesses$1.invoke(Unknown Source:12)
	at okio.Utf8.withProgress(Unknown Source:173)
	at okio.Utf8.withProgress$default(Unknown Source:8)
	at eu.darken.sdmse.appcleaner.core.AppCleaner.performDelete(Unknown Source:261)
	at eu.darken.sdmse.appcleaner.core.AppCleaner$performDelete$1.invokeSuspend(Unknown Source:12)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:107)
	at androidx.room.TransactionExecutor$1.run(Unknown Source:14)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Unknown Source:93)
`

**Comment by E0697** [comment]
It also seems like the app doesn't handle the permanent access properly.
The first time access is granted it works. When the app is relaunched however, it keeps waiting for link with Shizuku until I disable access from Shizuku app and request it again.

**Comment by d4rken** [comment]
Can you get me a log of the app relaunch issue?

**Comment by E0697** [comment]
Just tried reproducing it and it seems like it was a one-off. Sorry about that. Will report if it happens again.

**Comment by d4rken** [comment]
If you go into settings and setup, what does it say for Shizuku? The link status currently reflects whether SD Maids Shizuku Services could be launched.

The trim caches issue might be another R8 issue, will look into it later.

**Comment by E0697** [comment]
It says waiting for link with Shizuku.

It just happened again but wasn't triggered by a relaunch I think.

I tried switching between "Don't use/Use Shizuku" but it doesn't help.
Here's the (log)[https://pixeldrain.com/u/uj3nUSWG]

**Comment by d4rken** [comment]
Wondering if the setup is buggy there or if the service is really not working 🧐.

If you enable the debug mode and go to the debug card, there should be a "test Shizuku" button, if you have time check what it says.

**Comment by E0697** [comment]
I tried testing other apps with Shizuku and it's working.

Here's the output from test Shizuku:
![Screenshot_2023-06-28-16-23-35-19_a65106d178f5bee05a749e7f17331c4b.jpg](https://github.com/d4rken-org/sdmaid-se/assets/66939100/42091d1b-30e8-480f-8fef-ae40e393538b)
