### ISSUE TITLE
Storage Analyzer closes with NullPointerException

### ISSUE THREAD

**Issue by Vildanoff** [d4rken-org/sdmaid-se#463]
Device Xperia 1III
Android 13
non root
SD Maid SE 0.10.3
Storage Analyzer closes with NullPointerException
`W/SDMSE:Analyzer:Storage:Content:ViewModel: Storage unavailable StorageContentFragmentArgs(storageId=StorageId(internalId=null, externalId=41217664-9172-527a-b3d5-edabb50a7d69)): java.lang.NullPointerException: pkg.packageInfo.applicationInfo.dataDir must not be null
	at eu.darken.sdmse.analyzer.core.storage.StorageScanner.processPkg(Unknown Source:1197)
	at eu.darken.sdmse.analyzer.core.storage.StorageScanner.access$scanForApps(Unknown Source:363)
	at eu.darken.sdmse.analyzer.core.storage.StorageScanner$scanForApps$1.invokeSuspend(Unknown Source:12)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:107)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Unknown Source:93)`
Under the same conditions on SDM SE 0.10.2 Everything works

**Comment by d4rken** [comment]
I hope that this is fixed by #462
Please report back after the next update :heart:

**Comment by Vildanoff** [comment]
> Я надеюсь, что это исправлено #462 .

Fine. As soon as I get the update. I will check and post the result
