### ISSUE TITLE
Freeze app through ad command

### ISSUE THREAD

**Issue by adifrank** [d4rken-org/sdmaid-se#476]
As Shizuku randomly stops working and due to it sd maids features using it also stops working.

**Describe the solution you'd like**
So is it possible to use adb command like tasker uses to freeze the apps without root.

adb shell pm grant net.dinglisch.android.taskerm android.permission.WRITE_SECURE_SETTINGS

**Describe why this would be in the interest of all users**
Many of users don't want to root as many app stop working if you have rooted not matter how much root hide you use. And shizuku randomly stopping is common occurrence as I got to know. So it would be better if it can be done via this method. I have used it on tasker and there was no issue with it.

**Additional context**
https://developer.android.com/reference/android/Manifest.permission#WRITE_SECURE_SETTINGS
http://androidpermissions.com/permission/android.permission.WRITE_SECURE_SETTINGS
https://tasker.joaoapps.com/userguide/en/help/ah_secure_setting_grant.html

**Comment by d4rken** [comment]
I've looked into this a bit more and I don't think `WRITE_SECURE_SETTINGS` allows an app to disable packages or components.

There is another permission though called `CHANGE_COMPONENT_ENABLED_STATE`:

https://developer.android.com/reference/android/Manifest.permission#CHANGE_COMPONENT_ENABLED_STATE

This sounds like it could also be granted via ADB shell and give SD Maid the option to disable components/packages, i.e. apps.

**Comment by adifrank** [comment]
Yes it looks like it.
But tasker uses that WRITE_SECURE_SETTINGS thats why I thought that can be used for that purpose.
So can it be implemented.

**Comment by d4rken** [comment]
Looks like it's not possible. Can't grant it via ADB.

```java
Exception occurred while executing 'grant':
java.lang.SecurityException: Permission android.permission.CHANGE_COMPONENT_ENABLED_STATE requested by eu.darken.sdmse is not a changeable permission type
	at com.android.server.pm.permission.PermissionManagerService.grantRuntimePermissionInternal(PermissionManagerService.java:1565)
	at com.android.server.pm.permission.PermissionManagerService.grantRuntimePermission(PermissionManagerService.java:1493)
	at android.permission.PermissionManager.grantRuntimePermission(PermissionManager.java:378)
	at com.android.server.pm.PackageManagerShellCommand.runGrantRevokePermission(PackageManagerShellCommand.java:2448)
	at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:272)
	at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97)
	at android.os.ShellCommand.exec(ShellCommand.java:38)
	at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:29795)
	at android.os.Binder.shellCommand(Binder.java:986)
	at android.os.Binder.onTransact(Binder.java:860)
	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:5411)
	at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:9921)
	at android.os.Binder.execTransactInternal(Binder.java:1220)
	at android.os.Binder.execTransact(Binder.java:1179)
```
