### ISSUE TITLE
Read Exception error in corpse finder

### ISSUE THREAD

**Issue by catgangdev** [d4rken-org/sdmaid-se#592]
**Describe the bug**
Got Read Exception error in corpse finder for some entries.

**To Reproduce**
1. Go to ' Home '
2. Click on ' Scan under corpse finder '
3. Click 'Clear'

**Smartphone (please complete the following information):**
 - Device: [Xiaomi Redmi note 10 Pro]
 - OS: [Android 13]
 - Root status [Rooted - Magisk v26.1]
 - SD Maid 2/SE version [v0.11.0-beta0]

**Debug log**

[eu.darken.sdmse_logfile_1692235079588.log.zip](https://github.com/d4rken-org/sdmaid-se/files/12365246/eu.darken.sdmse_logfile_1692235079588.log.zip)

**Screenshots/Video**
![Screenshot_20230817-064542_SD Maid SE](https://github.com/d4rken-org/sdmaid-se/assets/62982051/f5db76c3-4d01-46be-8f97-5700c99984d3)

**Comment by d4rken** [comment]
Is this still happening?

I can't see a specific reason in the logs, just that it fails.

```java
eu.darken.sdmse.common.files.ReadException: Can't read from path. <-> /data/app/~~6Hkqk74caRE-9AqEyNWgdw==/catch_.me_.if_.you_.can_-lLXpV6n9yGVKyDWYKXXVOQ==
	at eu.darken.sdmse.common.files.local.LocalGateway$listFiles$3.invokeSuspend(Unknown Source:369)
	at eu.darken.sdmse.common.files.local.LocalGateway$listFiles$3.invoke(Unknown Source:12)
	at eu.darken.sdmse.common.files.local.LocalGateway$runIO$2.invokeSuspend(Unknown Source:32)
	at eu.darken.sdmse.common.files.local.LocalGateway$runIO$2.invoke(Unknown Source:12)
	at okio.Okio.startUndispatchedOrReturn(Unknown Source:4)
	at okio.Okio.withContext(Unknown Source:74)
	at eu.darken.sdmse.common.files.local.LocalGateway.runIO(Unknown Source:13)
	at eu.darken.sdmse.common.files.local.LocalGateway.listFiles(Unknown Source:9)
	at eu.darken.sdmse.common.files.GatewaySwitch$listFiles$2.invokeSuspend(Unknown Source:32)
	at eu.darken.sdmse.common.files.GatewaySwitch$listFiles$2.invoke(Unknown Source:12)
	at eu.darken.sdmse.common.files.GatewaySwitch.useGateway(Unknown Source:86)
	at eu.darken.sdmse.common.files.GatewaySwitch.listFiles(Unknown Source:6)
	at eu.darken.sdmse.common.files.APathExtensionsKt.deleteAll(Unknown Source:162)
	at eu.darken.sdmse.common.files.APathExtensionsKt.deleteAll(Unknown Source:204)
	at eu.darken.sdmse.common.files.APathExtensionsKt$deleteAll$1.invokeSuspend(Unknown Source:10)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:107)
	at androidx.room.TransactionExecutor$1.run(Unknown Source:30)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Unknown Source:93)
Caused by: java.io.IOException: Failed to listFiles() on /data/app/~~6Hkqk74caRE-9AqEyNWgdw==/catch_.me_.if_.you_.can_-lLXpV6n9yGVKyDWYKXXVOQ==
	at eu.darken.sdmse.common.files.local.ipc.FileOpsClient.fakeIOException(Unknown Source:62)
	at eu.darken.sdmse.common.files.local.ipc.FileOpsClient.listFilesStream(Unknown Source:76)
	at eu.darken.sdmse.common.files.local.LocalGateway$listFiles$3$4.invokeSuspend(Unknown Source:9)
	at eu.darken.sdmse.common.files.local.LocalGateway$listFiles$3$4.invoke(Unknown Source:12)
	at eu.darken.sdmse.common.files.local.LocalGateway$rootOps$2.invokeSuspend(Unknown Source:32)
	at eu.darken.sdmse.common.files.local.LocalGateway$rootOps$2.invoke(Unknown Source:12)
	at eu.darken.sdmse.common.root.service.RootServiceClientExtensionsKt$runModuleAction$2.invokeSuspend(Unknown Source:127)
	at eu.darken.sdmse.common.root.service.RootServiceClientExtensionsKt$runModuleAction$2.invoke(Unknown Source:12)
	at eu.darken.sdmse.common.root.service.RootServiceClient.runSessionAction(Unknown Source:129)
	at eu.darken.sdmse.common.files.local.LocalGateway.access$rootOps(Unknown Source:17)
	at eu.darken.sdmse.common.files.local.LocalGateway$listFiles$3.invokeSuspend(Unknown Source:176)
	... 19 more
```

```java
2023-08-17T01:18:29.088Z  E/SDMSE:FileOps:Service:Host:Root: lookupFiles(path=LocalPath(/data/app/~~6Hkqk74caRE-9AqEyNWgdw==/catch_.me_.if_.you_.can_-lLXpV6n9yGVKyDWYKXXVOQ==)) failed
java.io.IOException: Failed to listFiles() on /data/app/~~6Hkqk74caRE-9AqEyNWgdw==/catch_.me_.if_.you_.can_-lLXpV6n9yGVKyDWYKXXVOQ==
	at okio.Utf8.listFiles2(Unknown Source:40)
	at eu.darken.sdmse.common.files.local.ipc.FileOpsHost.listFilesStream(Unknown Source:47)
	at eu.darken.sdmse.common.files.local.ipc.FileOpsConnection$Stub.onTransact(Unknown Source:1431)
	at android.os.Binder.execTransactInternal(Binder.java:1280)
	at android.os.Binder.execTransact(Binder.java:1244)
```
