### ISSUE TITLE
Root/Shizuku does not work on bleeding edge build

### ISSUE THREAD

**Issue by chaoscalm** [d4rken-org/sdmaid-se#689]
```FATAL EXCEPTION: javaroot:RootConnectionReceiver#67f092b0-3f95-400b-84ff-0909f28af53a
Process: eu.darken.sdmse, PID: 27680
kotlin.io.FileSystemException: Failed to get user connection
	at eu.darken.sdmse.common.root.service.internal.RootHostLauncher$createConnection$1$ipcReceiver$1.onConnect(Unknown Source:97)
	at eu.darken.sdmse.common.root.service.internal.RootConnectionReceiver.doOnConnect(Unknown Source:23)
	at eu.darken.sdmse.common.root.service.internal.RootConnectionReceiver.access$doOnConnect(Unknown Source:0)
	at androidx.core.app.ActivityCompat$$ExternalSyntheticLambda0.run(Unknown Source:24)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by chaoscalm** [comment]
Latest commit https://github.com/d4rken-org/sdmaid-se/commit/c461a53fbf020a337617040ae7600380d8360812 cause this error on self-build.

**Comment by chaoscalm** [comment]
As I think that is w.i.p. I close this issue and keep for reference for whoever build in this moment.

**Comment by d4rken** [comment]
Re-open until I can reproduce/look into it.

When does the error occur?

**Comment by chaoscalm** [comment]
The error occurs as soon as I allow root permissions from the Magisk app, doesn't happen when not using root. I can reproduce it on different devices.

**Comment by d4rken** [comment]
That was a good spot :+1: , see PR #705 for an explanation.
