### ISSUE TITLE
AppCleaner not working properly

### ISSUE THREAD

**Issue by due3die** [d4rken-org/sdmaid-se#809]
**Describe the bug**
AppCleaner not working properly, when we run the cleaning it won't do its job. Please find an attached screencast for your reference.

**To Reproduce**
1. Go to 'AppCleaner'
2. Click on 'Scan Files'
3. Click on 'Delete'

**Expected behavior**
AppCleaner will clean the App Clear Cache and make a free space.

**Smartphone (please complete the following information):**
 - Device: [OnePlus 11]
 - OS: [Android 14 beta 4]
 - Root status [Non-Rooted]
 - SD Maid 2/SE version [v0.16.6-beta0]

**Debug log**
Reproduced the bug and recorded the event in https://drive.google.com/file/d/1jslnjD_v4C9hyqBc0C_8A5ttw1xk9phd/view?usp=drivesdk

**Screenshots/Video**
https://photos.app.goo.gl/uax7koCRWCx198DSA

**Additional context**
Kindly follow the above links for Log & Screencast.

**Comment by d4rken** [comment]
Thanks, for the video. Where can I find the debug log?

**Comment by due3die** [comment]
> Thanks, for the video. Where can I find the debug log?

I have attached the same.

https://drive.google.com/file/d/1jslnjD_v4C9hyqBc0C_8A5ttw1xk9phd/view?usp=drivesdk

**Comment by ReapCloud7O7** [comment]
Hi There Im new here .
I am facing a new problem after android 14 beta update 
Device oneplus 10r 
Android version 14
Issue is app cleaner keep on trying to clean one app cache for about 30 to 40 seconds the dialogue box is opening for several time then after its moving on for other app i have paid version. No use after and 14 beta update. Hope you find a solution quick. Thanks in advance.

**Comment by Clydeman10** [comment]
Perhaps I'm not in the right place to ask this question??Can I ask if this software can be ran on Firesticks and Nvidia Shields?Thanks.

**Comment by d4rken** [comment]
I'm not sure this is fixable from app-side.

The underlying issue is that the system does not return the current window back to SD Maid.

It's curious though that this is sporadic. Based on the logfile, it sometimes works and sometimes doesn't.

```java
2023-11-10T23:16:28.002Z  V/SDMSE:Automation:Crawler:Common: Looking for window identifiers: [com.readdle.spark, Spark, com.readdle.spark.app.SparkApp]
2023-11-10T23:16:28.003Z  D/SDMSE:Automation:Crawler: crawl(): Spec(parent=SDMSE:AppCleaner:Automation:OnePlus:Specs, label=Find & click 'Storage' (targets=[Storage usage]))
2023-11-10T23:16:28.003Z  V/SDMSE:Automation:Crawler: doCrawl(): Attempt 0 for Spec(parent=SDMSE:AppCleaner:Automation:OnePlus:Specs, label=Find & click 'Storage' (targets=[Storage usage]))
2023-11-10T23:16:28.003Z  V/SDMSE:Automation:Crawler: Launching window intent: Intent { act=android.settings.APPLICATION_DETAILS_SETTINGS dat=package: flg=0x10818000 }
2023-11-10T23:16:28.004Z  V/SDMSE:Automation:ScreenState: state.onStart()
2023-11-10T23:16:28.005Z  V/SDMSE:Automation:ScreenState: state.onEach(): State(isScreenOn=true, isUnlocked=true)
2023-11-10T23:16:28.046Z  V/SDMSE:Automation:Service: Updating progress kotlinx.coroutines.flow.StateFlowImpl@febc1b
2023-11-10T23:16:28.098Z  V/SDMSE:Automation:Service: Updating progress kotlinx.coroutines.flow.StateFlowImpl@febc1b
2023-11-10T23:16:28.225Z  V/SDMSE:Automation:Crawler: Waiting for window event filter to pass...
2023-11-10T23:16:28.992Z  V/SDMSE:Automation:Service: New automation event: EventType: TYPE_VIEW_CLICKED; EventTime: 884733; PackageName: com.android.settings; MovementGranularity: 0; Action: 16; ContentChangeTypes: []; WindowChangeTypes: [] [ ClassName: android.widget.Button; Text: [Clear cache]; ContentDescription: null; ItemCount: -1; CurrentItemIndex: -1; Enabled: false; Password: false; Checked: false; FullScreen: false; Scrollable: false; ImportantForAccessibility: true; AccessibilityDataSensitive: false; BeforeText: null; FromIndex: -1; ToIndex: -1; ScrollX: 0; ScrollY: 0; MaxScrollX: 0; MaxScrollY: 0; ScrollDeltaX: -1; ScrollDeltaY: -1; AddedCount: -1; RemovedCount: -1; ParcelableData: null; DisplayId: 0 ]; recordCount: 0
2023-11-10T23:16:28.995Z  V/SDMSE:Automation:Service: Fallback root was null, now is null
2023-11-10T23:16:29.045Z  V/SDMSE:Automation:Service: Providing event: EventType: TYPE_VIEW_CLICKED; EventTime: 884733; PackageName: com.android.settings; MovementGranularity: 0; Action: 16; ContentChangeTypes: []; WindowChangeTypes: [] [ ClassName: android.widget.Button; Text: [Clear cache]; ContentDescription: null; ItemCount: -1; CurrentItemIndex: -1; Enabled: false; Password: false; Checked: false; FullScreen: false; Scrollable: false; ImportantForAccessibility: true; AccessibilityDataSensitive: false; BeforeText: null; FromIndex: -1; ToIndex: -1; ScrollX: 0; ScrollY: 0; MaxScrollX: 0; MaxScrollY: 0; ScrollDeltaX: -1; ScrollDeltaY: -1; AddedCount: -1; RemovedCount: -1; ParcelableData: null; DisplayId: 0 ]; recordCount: 0
2023-11-10T23:16:29.045Z  V/SDMSE:Automation:Crawler: Testing window event EventType: TYPE_VIEW_CLICKED; EventTime: 884733; PackageName: com.android.settings; MovementGranularity: 0; Action: 16; ContentChangeTypes: []; WindowChangeTypes: [] [ ClassName: android.widget.Button; Text: [Clear cache]; ContentDescription: null; ItemCount: -1; CurrentItemIndex: -1; Enabled: false; Password: false; Checked: false; FullScreen: false; Scrollable: false; ImportantForAccessibility: true; AccessibilityDataSensitive: false; BeforeText: null; FromIndex: -1; ToIndex: -1; ScrollX: 0; ScrollY: 0; MaxScrollX: 0; MaxScrollY: 0; ScrollDeltaX: -1; ScrollDeltaY: -1; AddedCount: -1; RemovedCount: -1; ParcelableData: null; DisplayId: 0 ]; recordCount: 0
2023-11-10T23:16:29.045Z  V/SDMSE:Automation:Crawler: Waiting for window event filter passed!
2023-11-10T23:16:29.053Z  V/SDMSE:Automation:Service: Providing window root: null
2023-11-10T23:16:29.054Z  W/SDMSE:Automation:Crawler: crawl(): Attempt 1 failed on Spec(parent=SDMSE:AppCleaner:Automation:OnePlus:Specs, label=Find & click 'Storage' (targets=[Storage usage])):
io.github.z4kn4fein.semver.VersionFormatException: Root node is currently null
	at eu.darken.sdmse.automation.core.AutomationService.windowRoot(Unknown Source:103)
	at eu.darken.sdmse.automation.core.common.StepProcessor$doCrawl$targetWindowRoot$1.invokeSuspend(Unknown Source:178)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:107)
	at com.android.billingclient.api.zzl.run(Unknown Source:33)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Unknown Source:93)
```

**Comment by d4rken** [comment]
Don't have a solution for this. Based on the current information, it's a ROM issue. Feel free to reopen if more information comes up.

**Comment by thousandecibels** [comment]
Can confirm, I am using OnePlus 11 and I am facing the same issue with Android 14 and Android 13 versions of OxygenOS (ColorOS).
